// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dc7e15d1-c5d8-40f0-b1f8-9152b953899a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9tsa2Oyjj",
    "aws_user_pools_web_client_id": "3ldfbpq03grng4j1v0rlna6sea",
    "aws_appsync_graphqlEndpoint": "https://3dlpkppivrarnftotsmh3ednga.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wlrsvqfaengd3onixqevqqmipe"
};


export default awsmobile;
